#!/bin/bash
test -z "$1" && exit 1

eval `cat doinst | grep ^FILES=`

echo "installing to: $1..."
/usr/local/bin/timeout 60 /usr/local/lib/tools/admssh $1 "/usr/bin/sudo su - root -c \"rm -f $FILES\""
ip=$(nslookup $1 | awk 'NR>3 && /Address:/{print $2}')
test -z "$ip" && ip=$1
#echo $ip
cat getconf.template | sed "s:++MYWAY++:$ip:" > getconf
/usr/local/bin/timeout 60 /usr/local/lib/tools/admscp $FILES doinst $1:/tmp
test $? -ne 0 && exit 1
cmd="cd /tmp && sh doinst; rm -f doinst"
/usr/local/bin/timeout 60 /usr/local/lib/tools/admssh $1 "/usr/bin/sudo su - root -c \"$cmd\""
rm -f getconf
