#!/usr/bin/perl
use CGI;

my $debug = 0;
sub dprintf { my $level = shift; printf(@_) if ($debug >= $level); }

my $SERVER = "tools.uprd.usoncology.unx";

my $q = new CGI;
print $q->header();

my $ServerName = $q->param('ServerName');
$ServerName = "invalid" unless($ServerName);
$ServerName = $ARGV[0] if (length($ARGV[0]) > 0);
dprintf(1,"ServerName: %s\n", $ServerName);
$ServerName =~ tr/[a-zA-Z0-9\.//c;
dprintf(1,"calling $SERVER with: $ServerName...\n");
my $wg = "/usr/bin/curl -s -S -N \'http://$SERVER/cgi-bin/volconfig?ServerName=$ServerName\'";
dprintf(1,"wg: %s\n", $wg);
open(WG,"$wg |");
while(<WG>) { print }
close(WG); wait;
