#!/bin/bash
#
if test "$1" = "-n"; then no_head=1; shift; else no_head=0; fi
if test "$1" = "-x"; then no_head=1; x_opt=1; shift; else x_opt=0; fi

if test -z "$1"; then
	echo "usage: cvm <esx host>"
	exit 1
fi

if test $x_opt -eq 0; then vminfo_opt="-n"; else vminfo_opt="-x"; fi
SERVER=$1

tmpdir=/dev/shm
tmp1=$tmpdir/cvm1.$$
tmp2=$tmpdir/cvm2.$$

cleanup() {
#	echo "cleaning up..."
	rm -f $tmp1 $tmp2
	exit 1
}
trap cleanup SIGINT SIGTERM

fixup()
{
        echo "$1" | awk '{
                str=""
                for(i=1; i < length($0)+1; i++) {
                        c=substr($0,i,1);
                        if ((c >= "a" && c <= "z") || (c >= "A" && c <= "Z") || (c >= '0' && c <= '9')) {
                                str = str tolower(c);
                        } else {
                                break;
                        }
                }
                print str;
        }'
}

/usr/local/bin/esxconf -s $SERVER -t VirtualMachine -n > $tmp2
if test $? -ne 0; then
	cat $tmp2
	rm -rf $tmp2
	exit 1
fi
cat $tmp2 | awk '{ print $2 }' > $tmp1
if test $no_head -eq 0; then
format="%-16.16s  %-25.25s  %-40.40s  %-18.18s  %-14.14s  %-12.12s\n";
printf "$format" "Farm" "Host" "VM" "SLA" "Status" "Environ"
printf "$format" "-----------------------------" "------------------------------" "------------------------------" "------------------" "-------------------" "--------------"
fi
while read obj
do
#	echo $obj
	/usr/local/bin/esxconf -s $SERVER -o $obj -e name config.hardware > $tmp2
	if test `cat $tmp2 | grep -c physicalSharing` -gt 0; then
		n=`cat $tmp2 | grep name=`
		eval $n
		echo $name
#		n=`fixup $name`
		n=$name
		vminfo $vminfo_opt $n
	fi
done < $tmp1
rm -f $tmp1 $tmp2
