
#ifndef __HOSTS_H
#define __HOSTS_H

/*
*** this file is automatically generated - DO NOT MODIFY
*/

#include "db.h"

/* Structure definition for the hosts table */
struct hosts_record {
	int id;
	int farm_id;
	char name[65];
	char model[33];
	char status[17];
	char version[9];
	int build;
	float psp;
	int cpu_pkgs;
	int cpu_count;
	int cpu_total;
	int cpu_speed;
	int mem_total;
	int cons_mem;
	char subnet[17];
	char last_seen[20];
	char in_maint[9];
};
#define hosts_field_count 17
int hosts_select(DB *db, char *clause);
int hosts_select_record(DB *db, struct hosts_record *rec, char *clause);
int hosts_insert(DB *db, struct hosts_record *rec);
int hosts_update_record(DB *db, struct hosts_record *rec, char *clause);
int hosts_fetch(DB *db);
int hosts_fetch_record(DB *db, struct hosts_record *rec);

#endif /* __HOSTS_H */
