#!/usr/bin/perl
use strict;
use CGI;

my $debug = 1;

my $myname = `hostname`; chomp($myname);
sub dprintf { my $level = shift; if ($debug >= $level) { print "#[$myname] "; printf(@_); } }

my $q = new CGI;
print $q->header();

my $host = $q->param('host');
$host = "invalid" unless($host);
$host = $ARGV[0] if ($ARGV[0]);
dprintf(1,"host: %s\n", $host);
my $key = $q->param('key');
$key = "" unless($key);
$key = $ARGV[1] if ($ARGV[1]);
dprintf(1,"key: %s\n", $key);
my $cmd = "/usr/local/sbin/esxpost -m ";
$cmd .= "-j -k \"$key\" " if (length($key));
$cmd .= "$host";
dprintf(1,"cmd: %s\n", $cmd);
system("echo [`date`] $cmd >> /var/tmp/esxpost.log");
system($cmd);
exit 0;
