#!/bin/bash
test -z "$1" && exit 1
host="$1"
echo $host
# -e option doesnt exist on 3.5
me=`readlink -f $0`
#echo "host: $host"
if test "$host" = "doit"; then
	rpm -q hpit-san-tools
	if test $? -ne 0; then
		if test -e /usr/bin/apt-get; then
			apt-get -y install hpit-san-tools
		else
			yum -y install hpit-san-tools
		fi
	fi
	/usr/local/bin/path_check v
	r=$?
	rm -f $me
	exit $r
else
	script=`basename $me`
	scp -B -o ConnectTimeout=5 $me $host:/tmp > /dev/null
	test $? -ne 0 && exit 1
	ssh -n -q -o BatchMode=yes $host "sudo su root -c \"chmod +x /tmp/$script; /tmp/$script doit\"" > /tmp/$host
	if test $? -ne 0; then
		echo fail
		echo "********** $host ************" >> /tmp/body
		cat /tmp/$host >> /tmp/body
	fi
fi
