#!/bin/bash
#
THREADS=1
#
me=`readlink -e $0`
dir=`dirname $me`
flag=/tmp/esxpaths.running
trap '{ echo "Aborting." ; rm -f $flag; exit 1; }' INT
if test -f $flag; then
	echo "esxpaths already running, aborting."
	exit 0
fi
echo "`date` starting"
touch $flag
/usr/local/bin/worker $HOME/etc/esxservers $THREADS $dir/do_pathcheck
echo "`date` finished"
rm -f $flag
