#!/bin/bash
test -z "$1" && exit 1
#mysql -N -B -e "SELECT name FROM esx_build_name WHERE build = '$1'"
mysql -N -B -e "select name from esx_build_name where build = (select build from hosts where name regexp '$1')"
