#!/usr/bin/perl
use strict;
use warnings;
use Data::Dumper;
use XML::Simple;
use VMware::VIRuntime;
#use feature "switch";

my $debug = 1;
sub dprintf { my $level = shift; if ($debug >= $level) { print "#"; printf(@_); } }

Opts::parse();
Opts::validate();
Util::connect();

my $url = "https://$server/sdk";

Util::connect(url, 'user', 'pass');

#my ($url, $username, $password) = @_;
#my ($url, $username, $password) = @_;

my @host_networks = @{ Vim::get_views(mo_ref_array => $host->network) };
print Dumper(@host_networks);
my %networks = map { $_->name => $_ } @host_networks;
print Dumper(%networks);

Util::disconnect();
