#!/usr/bin/perl
use strict;
use warnings;
use DBI;

my $ESXADMIN_SERVER = "itxadmin.hp.com";

my $dbh = DBI->connect("DBI:mysql:esxadmin:$ESXADMIN_SERVER",'esx_ro') or die "Couldn't connect to database: " . DBI->errstr;
my $farms = $dbh->prepare("SELECT id FROM farms WHERE name like ?");
my $hosts = $dbh->prepare("SELECT name FROM hosts WHERE farm_id = ? ORDER BY name");
my $admssh = "/usr/local/lib/tools/admssh";

if ($#ARGV < 1) {
        print "usage: farmcmd <farm> <cmd>\n";
        exit 1;
}

my $arg = shift;
#$ARGV[0];
my $cmd = "";
for (my $i = 0; $i <= $#ARGV; $i++) {
	$cmd = $cmd . $ARGV[$i] . " ";
}
#printf("cmd: %s\n", $cmd);
        my ($name) = $arg;
#       printf("farm: %s\n", $name);
        $farms->execute($name . "%");
        if (not $farms->rows) {
                printf("farmcmd: farm %s not found.\n", $name);
                exit 1;
        }
        my @data = $farms->fetchrow;
        my ($id) = @data;
	my $str;
        $hosts->execute($id);
        while(my @data = $hosts->fetchrow_array()) {
#		printf("host: %s\n", $data[0]);
		$str="$admssh " . $data[0] . " \"" . $cmd . "\"";
		printf("%s\n", $str);
		system($str);
        }

