#!/bin/bash

NAME=esxconf
ARCH=`cat $NAME.spec.pre | grep BuildArch: | awk '{ print $2 }'`
ROOT=$HOME/rpmbuild/BUILDROOT/$NAME-1-0.$ARCH

mkspec() {
v=`cat version.h | awk '{ print $3 }'`
eval ver=$v
test -f release && rel=`cat release`
test -z "$rel" && rel=0
cat $NAME.spec.pre | sed "s:<VERSION>:$ver:" | sed "s:<RELEASE>:$rel:" > $NAME.spec
if test -f changelog; then
	echo "%changelog" >> $NAME.spec
	cat changelog >> $NAME.spec
fi
cp $NAME.spec.pre $NAME.spec
CWD=`pwd`
(cd $ROOT || exit 1; find . | sed "s:^\.::" > $CWD/$NAME.spec.files)
while read n
do
	test -z "$n" && continue
	test -f "$n" || continue
	stat --format="%%attr(%a,%U,%G) %n" "$n" >> $NAME.spec
done < $NAME.spec.files
rm -f $NAME.spec.files
}

make clean
make install BUILDROOT=$ROOT
mkspec
rpmbuild -bb $NAME.spec || exit 1
rm -f $NAME.spec
/usr/local/lib/tools/admscp $HOME/rpmbuild/RPMS/$ARCH/$NAME-1-0.$ARCH.rpm ddc-coe:/tmp
/usr/local/lib/tools/admssh ddc-coe "sudo bash -c \"mkdir -p /coe/usonforge/6/$ARCH; mv /tmp/$NAME-1-0.$ARCH.rpm /coe/usonforge/6/$ARCH; /root/syncer/mkrepo usonforge\""
