#!/bin/bash
RPASS=
db=`cat ~/.my.cnf | grep ^database= | awk -F= '{ print $2 }'`
user=`cat ~/.my.cnf | grep ^user= | awk -F= '{ print $2 }'`
pass=`cat ~/.my.cnf | grep ^password= | awk -F= '{ print $2 }'`
#MY="sudo mysql --database=mysql --user=root --password=$RPASS -e"
MY="sudo mysql --database=mysql --user=root -e"
doit() {
	$MY "drop user '${1}'@'${2}'" > /dev/null 2>&1
	if test -n "${4}"; then
		$MY "create user '${1}'@'${2}' IDENTIFIED BY '${4}'"
	else
		$MY "create user '${1}'@'${2}'"
	fi
	$MY "grant ${3} on ${db}.* to '${1}'@'${2}'"
}
doit "${db}_ro" "%%" "select" "${db}_ro"
doit "${db}_rw" "%%" "select,insert,update,delete" "${db}_rw"
doit "$user" "localhost" "all" "$pass"
$MY "FLUSH PRIVILEGES"
